/* ==============================
       Product Data
       ============================== */
// Loaded before script.js (see index.html) so PRODUCTS is a global by the time
// script.js's render functions read it. Keep this file focused on product
// listing/content — rendering logic lives in script.js.
//
// `warns`/`storage` below use an honest "coming soon" placeholder rather than
// invented ingredient/usage copy where real content isn't ready yet — swap
// `images`/`ingredients`/`how`/`tips` in as real content becomes available; empty
// arrays there just skip that section on the detail page (see renderDetail() in
// script.js), nothing breaks.
const PLACEHOLDER_WARNS = ["Full ingredient list and usage guidance coming soon — message us on Facebook if you have questions before ordering."];
const PLACEHOLDER_STORAGE = ["Store in a cool, dry place, away from direct sunlight and out of children's reach."];

const PRODUCTS = [
  // ---- Hair Care ----
  {
    id: "8",
    name: "Detox Shampoo Bar",
    subtitle: "Oily Scalp · 60g+",
    slug: "detox-shampoo-bar",
    price: 700,
    category: "Hair Care",
    images: ["./images/detox_shampoo_bar.webp"],
    short: "A detoxifying bar shampoo formulated for oily scalps.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    // Set to true to feature this product in the homepage "Top Selling Products" carousel.
    topSelling: false,
    // Set to "hot" / "new" / "sale" / "popular" (or leave null) — see README.MD.
    badge: null,
    display_order: null,
  },
  {
    // Was "Coming Soon" — now live with a real price/category; same id/slug kept for
    // Messenger ref continuity. Badged "new" per README's New Arrival convention.
    id: "6",
    name: "Silkroot Shampoo Bar",
    subtitle: "Sensitive Scalp · 60g+",
    slug: "silkroot-shampoo-bar",
    price: 700,
    category: "Hair Care",
    images: ["./images/silkRoot_shampoo_bar.webp"],
    short: "A gentle bar shampoo formulated for sensitive scalps.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    topSelling: false,
    badge: "new",
    display_order: null,
  },
  {
    id: "9",
    name: "Conditioner Bar",
    subtitle: "All Hair Types · 60g+",
    slug: "conditioner-bar",
    price: 750,
    category: "Hair Care",
    images: ["./images/conditioner_bar.webp"],
    short: "A nourishing bar conditioner suitable for all hair types.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    topSelling: true,
    badge: null,
    display_order: 1,
  },
  {
    // Was "Coming Soon" — now live with a real price/category; same id/slug kept for
    // Messenger ref continuity. Badged "new" per README's New Arrival convention.
    id: "4",
    name: "RoseMintClove Scalp Elixir",
    subtitle: "118ml",
    slug: "scalp-elixir",
    price: 550,
    category: "Hair Care",
    images: ["./images/rose_mint_clove_scalp_elixir.webp"],
    short: "A rose, mint & clove scalp elixir for hair and scalp care.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    topSelling: false,
    badge: "new",
    display_order: null,
  },
  // ---- Magnesium Oil Spray ----
  {
    id: "1",
    name: "Magnesium Oil Spray",
    subtitle: "30% Concentration · 100ml",
    slug: "magnesium-oil",
    price: 360,
    category: "Magnesium Oil Spray",
    images: [
      "./images/hayatiq_magnesium_oil_30.webp",
      "./images/hayatiq_magnesium_oil_2.jpg",
      "./images/hayatiq_magnesium_oil_3.jpg",
    ],
    short: "Nature’s Calm in Every Spray",
    ingredients: ["Magnesium Chloride Brine", "Lavender Essential Oil"],
    how: [
      "Daily Supplement: <b>Where</b>: Spread across arms, legs, stomach.; <b>How much</b>: 15–20 sprays total.; <b>When</b>: Split between morning & evening.;",
      "Muscle Cramps & Soreness:<b>Where</b>: Directly on cramped or sore muscles (calves, thighs, arms).; <b>How much</b>: 10–15 sprays.; <b>When</b>: During cramps, after workouts, or long days standing.; <b>Extra Tip</b>: Massage in for faster relief.;",
      "Sleep & Relaxation:<b>Where</b>: Soles of feet, back of neck, shoulders.; <b>How much</b>: 5–10 sprays.; <b>When</b>: 30 minutes before bedtime.; <b>Extra Tip</b>: Massage gently into skin for deeper relaxation.;",
      "Restless Legs Syndrome:<b>Where</b>: Calves, thighs.; <b>How much</b>: 10–15 sprays.; <b>When</b>: Before bedtime.;",
      "Bone & Joint Health:<b>Where</b>: Knees, elbows, lower back, wrists.; <b>How much</b>: 8–12 sprays.; <b>When</b>: Daily, preferably evening.;",
      "Headaches & Migraines:<b>Where</b>: Temples (lightly), back of neck, shoulders.; <b>How much</b>: 2–3 sprays.; <b>When</b>: At onset of headache/migraine.; <b>Extra Tip</b>: Soak feet in warm water + magnesium oil for additional relief. Spray on hand then rub it to temple.;",
      "Hair & Scalp Health:<b>Where</b>: Spray directly onto scalp (part hair).; <b>How much</b>: 5–8 sprays.; <b>When</b>: 2–3 times per week, before shower.; <b>Extra Tip</b>: Massage scalp, leave for 30 minutes, then wash.;",
      "Cramps & PMS Relief:<b>Where</b>: Lower abdomen, lower back.; <b>How much</b>: 8–12 sprays.; <b>When</b>: During cramps or PMS discomfort.; <b>Extra Tip</b>: Massage gently until absorbed.;",
      "Energy Boost & Fatigue Relief:<b>Where</b>: Arms, legs, stomach.; <b>How much</b>: 5–10 sprays.; <b>When</b>: Morning or mid-day slump.; <b>Extra Tip</b>: Pair with light stretching or deep breathing.;",
      "Deodorant:<b>Where</b>: Underarms (on clean, dry skin).; <b>How much</b>: 2–4 sprays per armpit.; <b>When</b>: Once daily (morning), reapply if needed.; <b>Extra Tip</b>: Wear clothing after fully absorbed.;",
      "Stress & Anxiety:<b>Where</b>: Chest, shoulders, behind ears (not too close to eyes).; <b>How much</b>: 5–8 sprays.; <b>When</b>: During stress, after work, or before meditation.;",
      "Exercise Recovery:<b>Where</b>: On exercised muscles (legs, arms, back).; <b>How much</b>: 10–15 sprays.; <b>When</b>: Right after workout or before bed.;",
    ],
    tips: [
      "Apply on clean skin, make sure there are no dead skin",
      "Consistent application is recommended for effective results",
      "A mild tingling sensation is normal and fades with regular use",
      "May dilute with water to ease tingling",
    ],
    warns: [
      "<b>Patch test first:</b>  Always test on a small area (inner wrist/leg) before first full use.",
      "<b>For external use only:</b>  Do not ingest unless specifically formulated for oral use.",
      "<b>Avoid sensitive areas:</b>  Do not spray near eyes, mouth, broken skin, cuts, or freshly shaved skin.",
      "<b>Skin sensitivity:</b>  A mild tingling, itching, or warmth is normal for first-time users. If irritation persists, rinse off and dilute with water before reapplying."
    ],
    storage: [
      "Keep bottle tightly sealed. Store in a cool, dry placeaway from direct sunlight, heat, or children’s reach.",
      "Use within 6 months of manufacture."
    ],
    // "Shop by Need" tags — drawn from this product's own `how` entries above (Sleep &
    // Relaxation, Muscle Cramps & Soreness, Stress & Anxiety), not invented. Powers the
    // homepage "Find the Right Product" tiles (see NEED_TILES). Leave [] if a product
    // doesn't clearly fit a listed need yet.
    concerns: ["Better Sleep", "Muscle Recovery"],
    // DEMO PREVIEW DATA — for layout preview only, replace with real reviews before
    // launch (see README.MD "Adding Customer Reviews"). Remove this comment and the
    // two entries below once real feedback is added.
    reviews: [
      { name: "Nusrat A.", rating: 5, text: "This has genuinely improved my sleep. A few sprays on my feet before bed and I feel so much more relaxed — the scent is mild too, no irritation at all. Highly recommend!" },
      { name: "Rakibul H.", rating: 4.5, text: "Using this for muscle cramps after workouts and it really helps. Had a bit of tingling the first couple of days but that faded quickly. Would love a bigger bottle option." },
    ],
    // Set to true to feature this product in the homepage "Top Selling Products" carousel.
    topSelling: false,
    badge: null,
    display_order: 7,
  },
  {
    id: "2",
    name: "Magnesium Oil Spray",
    subtitle: "50% Concentration · 100ml",
    slug: "magnesium-oil-50-concentration",
    price: 500,
    category: "Magnesium Oil Spray",
    images: [
      "./images/hayatiq_magnesium_oil_50.webp",
      "./images/hayatiq_magnesium_oil_2.jpg",
      "./images/hayatiq_magnesium_oil_3.jpg",
    ],
    short: "Nature’s Calm in Every Spray",
    ingredients: ["Magnesium Chloride Brine", "Lavender Essential Oil"],
    how: [
      "Daily Supplement: <b>Where</b>: Spread across arms, legs, stomach.; <b>How much</b>: 15–20 sprays total.; <b>When</b>: Split between morning & evening.;",
      "Muscle Cramps & Soreness:<b>Where</b>: Directly on cramped or sore muscles (calves, thighs, arms).; <b>How much</b>: 10–15 sprays.; <b>When</b>: During cramps, after workouts, or long days standing.; <b>Extra Tip</b>: Massage in for faster relief.;",
      "Sleep & Relaxation:<b>Where</b>: Soles of feet, back of neck, shoulders.; <b>How much</b>: 5–10 sprays.; <b>When</b>: 30 minutes before bedtime.; <b>Extra Tip</b>: Massage gently into skin for deeper relaxation.;",
      "Restless Legs Syndrome:<b>Where</b>: Calves, thighs.; <b>How much</b>: 10–15 sprays.; <b>When</b>: Before bedtime.;",
      "Bone & Joint Health:<b>Where</b>: Knees, elbows, lower back, wrists.; <b>How much</b>: 8–12 sprays.; <b>When</b>: Daily, preferably evening.;",
      "Headaches & Migraines:<b>Where</b>: Temples (lightly), back of neck, shoulders.; <b>How much</b>: 2–3 sprays.; <b>When</b>: At onset of headache/migraine.; <b>Extra Tip</b>: Soak feet in warm water + magnesium oil for additional relief. Spray on hand then rub it to temple.;",
      "Hair & Scalp Health:<b>Where</b>: Spray directly onto scalp (part hair).; <b>How much</b>: 5–8 sprays.; <b>When</b>: 2–3 times per week, before shower.; <b>Extra Tip</b>: Massage scalp, leave for 30 minutes, then wash.;",
      "Cramps & PMS Relief:<b>Where</b>: Lower abdomen, lower back.; <b>How much</b>: 8–12 sprays.; <b>When</b>: During cramps or PMS discomfort.; <b>Extra Tip</b>: Massage gently until absorbed.;",
      "Energy Boost & Fatigue Relief:<b>Where</b>: Arms, legs, stomach.; <b>How much</b>: 5–10 sprays.; <b>When</b>: Morning or mid-day slump.; <b>Extra Tip</b>: Pair with light stretching or deep breathing.;",
      "Deodorant:<b>Where</b>: Underarms (on clean, dry skin).; <b>How much</b>: 2–4 sprays per armpit.; <b>When</b>: Once daily (morning), reapply if needed.; <b>Extra Tip</b>: Wear clothing after fully absorbed.;",
      "Stress & Anxiety:<b>Where</b>: Chest, shoulders, behind ears (not too close to eyes).; <b>How much</b>: 5–8 sprays.; <b>When</b>: During stress, after work, or before meditation.;",
      "Exercise Recovery:<b>Where</b>: On exercised muscles (legs, arms, back).; <b>How much</b>: 10–15 sprays.; <b>When</b>: Right after workout or before bed.;",
    ],
    tips: [
      "Apply on clean skin, make sure there are no dead skin",
      "Consistent application is recommended for effective results",
      "A mild tingling sensation is normal and fades with regular use",
      "May dilute with water to ease tingling",
    ],
    warns: [
      "<b>Patch test first:</b>  Always test on a small area (inner wrist/leg) before first full use.",
      "<b>For external use only:</b>  Do not ingest unless specifically formulated for oral use.",
      "<b>Avoid sensitive areas:</b>  Do not spray near eyes, mouth, broken skin, cuts, or freshly shaved skin.",
      "<b>Skin sensitivity:</b>  A mild tingling, itching, or warmth is normal for first-time users. If irritation persists, rinse off and dilute with water before reapplying."
    ],
    storage: [
      "Keep bottle tightly sealed. Store in a cool, dry placeaway from direct sunlight, heat, or children’s reach.",
      "Use within 6 months of manufacture."
    ],
    // See NEED_TILES — same usage guidance as the 30% variant above.
    concerns: ["Better Sleep", "Muscle Recovery"],
    // Fill in real customer reviews here as they come in — see README.MD.
    reviews: [],
    topSelling: false,
    badge: null,
    display_order: 6,
  },
  {
    id: "10",
    name: "Magnesium Oil Spray",
    subtitle: "2x Strength · 130ml",
    slug: "magnesium-oil-2x-strength",
    price: 850,
    category: "Magnesium Oil Spray",
    images: ["./images/hayatiq_magnesium_oil_2x.webp"],
    short: "Nature’s Calm in Every Spray — now in extra strength.",
    ingredients: ["Magnesium Chloride Brine", "Lavender Essential Oil"],
    // Same usage guidance as the 30%/50% variants (same formula, higher concentration)
    // — see NEED_TILES comment on the 50% variant above.
    how: [
      "Daily Supplement: <b>Where</b>: Spread across arms, legs, stomach.; <b>How much</b>: 15–20 sprays total.; <b>When</b>: Split between morning & evening.;",
      "Muscle Cramps & Soreness:<b>Where</b>: Directly on cramped or sore muscles (calves, thighs, arms).; <b>How much</b>: 10–15 sprays.; <b>When</b>: During cramps, after workouts, or long days standing.; <b>Extra Tip</b>: Massage in for faster relief.;",
      "Sleep & Relaxation:<b>Where</b>: Soles of feet, back of neck, shoulders.; <b>How much</b>: 5–10 sprays.; <b>When</b>: 30 minutes before bedtime.; <b>Extra Tip</b>: Massage gently into skin for deeper relaxation.;",
      "Restless Legs Syndrome:<b>Where</b>: Calves, thighs.; <b>How much</b>: 10–15 sprays.; <b>When</b>: Before bedtime.;",
      "Bone & Joint Health:<b>Where</b>: Knees, elbows, lower back, wrists.; <b>How much</b>: 8–12 sprays.; <b>When</b>: Daily, preferably evening.;",
      "Headaches & Migraines:<b>Where</b>: Temples (lightly), back of neck, shoulders.; <b>How much</b>: 2–3 sprays.; <b>When</b>: At onset of headache/migraine.; <b>Extra Tip</b>: Soak feet in warm water + magnesium oil for additional relief. Spray on hand then rub it to temple.;",
      "Hair & Scalp Health:<b>Where</b>: Spray directly onto scalp (part hair).; <b>How much</b>: 5–8 sprays.; <b>When</b>: 2–3 times per week, before shower.; <b>Extra Tip</b>: Massage scalp, leave for 30 minutes, then wash.;",
      "Cramps & PMS Relief:<b>Where</b>: Lower abdomen, lower back.; <b>How much</b>: 8–12 sprays.; <b>When</b>: During cramps or PMS discomfort.; <b>Extra Tip</b>: Massage gently until absorbed.;",
      "Energy Boost & Fatigue Relief:<b>Where</b>: Arms, legs, stomach.; <b>How much</b>: 5–10 sprays.; <b>When</b>: Morning or mid-day slump.; <b>Extra Tip</b>: Pair with light stretching or deep breathing.;",
      "Deodorant:<b>Where</b>: Underarms (on clean, dry skin).; <b>How much</b>: 2–4 sprays per armpit.; <b>When</b>: Once daily (morning), reapply if needed.; <b>Extra Tip</b>: Wear clothing after fully absorbed.;",
      "Stress & Anxiety:<b>Where</b>: Chest, shoulders, behind ears (not too close to eyes).; <b>How much</b>: 5–8 sprays.; <b>When</b>: During stress, after work, or before meditation.;",
      "Exercise Recovery:<b>Where</b>: On exercised muscles (legs, arms, back).; <b>How much</b>: 10–15 sprays.; <b>When</b>: Right after workout or before bed.;",
    ],
    tips: [
      "Apply on clean skin, make sure there are no dead skin",
      "Consistent application is recommended for effective results",
      "A mild tingling sensation is normal and fades with regular use",
      "May dilute with water to ease tingling",
    ],
    warns: [
      "<b>Patch test first:</b>  Always test on a small area (inner wrist/leg) before first full use.",
      "<b>For external use only:</b>  Do not ingest unless specifically formulated for oral use.",
      "<b>Avoid sensitive areas:</b>  Do not spray near eyes, mouth, broken skin, cuts, or freshly shaved skin.",
      "<b>Skin sensitivity:</b>  A mild tingling, itching, or warmth is normal for first-time users — being the strongest concentration, patch-testing matters even more here. If irritation persists, rinse off and dilute with water before reapplying."
    ],
    storage: [
      "Keep bottle tightly sealed. Store in a cool, dry placeaway from direct sunlight, heat, or children’s reach.",
      "Use within 6 months of manufacture."
    ],
    concerns: ["Better Sleep", "Muscle Recovery"],
    reviews: [],
    topSelling: true,
    badge: "hot",
    display_order: 5,
  },
  // ---- Salves & Balms ----
  {
    id: "11",
    name: "Pain Relief Salve",
    subtitle: "70g",
    slug: "pain-relief-salve",
    price: 700,
    category: "Salves & Balms",
    images: ["./images/placeholder.webp"],
    short: "A topical salve for on-the-go pain relief.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    // Sourced from the product's own name/purpose, not invented usage guidance.
    concerns: ["Muscle Recovery"],
    reviews: [],
    topSelling: false,
    badge: null,
    display_order: null,
  },
  // ---- Bath Bombs ----
  {
    id: "12",
    name: "Bath Bomb",
    subtitle: "Botanical + Scent of Your Choice · 100g",
    slug: "bath-bomb",
    price: 220,
    category: "Bath Bombs",
    images: ["./images/hayatiq_bath_bomb_1.webp", "./images/hayatiq_bath_bomb_2.webp", "./images/hayatiq_bath_bomb_3.webp"],
    short: "A botanical bath bomb in your choice of scent.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    topSelling: true,
    badge: null,
    display_order: 8,
  },
  {
    id: "13",
    name: "Bath Bomb Set of 3",
    slug: "bath-bomb-set-of-3",
    price: 600,
    category: "Bath Bombs",
    images: ["./images/hayatiq_bath_bomb_set_1.webp", "./images/hayatiq_bath_bomb_1.webp" ],
    short: "A set of 3 botanical bath bombs.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    topSelling: false,
    badge: null,
    display_order: 9,
  },
  // ---- Footsoaks ----
  {
    id: "14",
    name: "Footsoak Pack of 3",
    subtitle: "Botanical + Scent of Your Choice · 60g each",
    slug: "footsoak-pack-of-3",
    price: 270,
    category: "Footsoaks",
    images: ["./images/hayatiq_footsoak.webp"],
    short: "A botanical foot soak, pack of 3.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    topSelling: false,
    badge: null,
    display_order: null,
  },
  // ---- Oral Care ----
  {
    id: "15",
    name: "Copper Tongue Scraper",
    subtitle: "Type A",
    slug: "copper-tongue-scraper",
    price: 650,
    category: "Oral Care",
    images: ["./images/hayatiq_copper_tongue_scraper.webp"],
    short: "A copper tongue scraper for daily oral hygiene.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    topSelling: true,
    badge: null,
    display_order: 4,
  },
  {
    id: "16",
    name: "Biodegradable Floss",
    subtitle: "Bottled",
    slug: "biodegradable-floss-bottled",
    price: 250,
    category: "Oral Care",
    images: ["./images/hayatiq_biodegradable_floss_1.webp", "./images/hayatiq_biodegradable_floss_2.webp"],
    short: "Biodegradable dental floss.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    topSelling: true,
    badge: null,
    display_order: null,
  },
  // ---- Cleaning Supply ----
  {
    id: "18",
    name: "Non Toxic Solid Dish Soap",
    slug: "dish-soap",
    category: "Cleaning Supply",
    short: "A non-toxic solid dish soap with bar and block options.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    topSelling: true,
    badge: "popular",
    display_order: 2,
    variants: [
      {
        id: "bar",
        label: "Bar",
        default: false,
        subtitle: "83g+",
        price: 190,
        images: ["./images/hayatiq_dish_soap_bar.webp"],
      },
      {
        id: "block",
        label: "Block",
        default: true,
        subtitle: "500g",
        price: 750,
        images: ["./images/hayatiq_dish_soap_block.webp"],
      }
    ],
  },
  {
    id: "20",
    name: "Non Toxic Toilet Cleaning Pods",
    subtitle: "Pack of 7 · 30g each",
    slug: "toilet-cleaning-pods",
    price: 370,
    category: "Cleaning Supply",
    images: ["./images/hayatiq_toilet_cleaning_pods.webp"],
    short: "Non-toxic toilet cleaning pods, pack of 7.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    topSelling: false,
    badge: null,
    display_order: null,
  },
  {
    id: "21",
    name: "Non Toxic Foaming Handwash Tablets",
    subtitle: "Pack of 2 · 500ml",
    slug: "handwash-tablets-pack-of-2",
    price: 200,
    category: "Cleaning Supply",
    images: ["./images/placeholder.webp"],
    short: "Non-toxic foaming handwash tablets.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    topSelling: false,
    badge: null,
    display_order: null,
  },
  {
    id: "22",
    name: "Non Toxic Foaming Handwash Tablets",
    subtitle: "Pack of 4 · 1000ml",
    slug: "handwash-tablets-pack-of-4",
    price: 380,
    category: "Cleaning Supply",
    images: ["./images/placeholder.webp"],
    short: "Non-toxic foaming handwash tablets.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    topSelling: false,
    badge: null,
    display_order: null,
  },
  {
    id: "23",
    name: "Non Toxic All Purpose Cleaning Tablets",
    subtitle: "Pack of 2 · 600ml",
    slug: "all-purpose-cleaning-tablets",
    price: 300,
    category: "Cleaning Supply",
    images: ["./images/placeholder.webp"],
    short: "Non-toxic all-purpose cleaning tablets.",
    ingredients: [],
    how: [],
    tips: [],
    warns: PLACEHOLDER_WARNS,
    storage: PLACEHOLDER_STORAGE,
    concerns: [],
    reviews: [],
    topSelling: false,
    badge: null,
    display_order: null,
  },
];

// Optional per-product `display_order` (number) controls listing order everywhere a
// product grid/carousel renders — ascending, lowest first (see README.MD). Sorting
// once here makes every render function that reads PRODUCTS honor it automatically.
// Unset (null) sorts last, after any product with an explicit order. Ties (equal
// display_order, or several unset) keep their relative array order — no tie-break
// needed since Array#sort is stable.
PRODUCTS.sort((a, b) => {
  const orderA = typeof a.display_order === "number" ? a.display_order : Infinity;
  const orderB = typeof b.display_order === "number" ? b.display_order : Infinity;
  return orderA - orderB;
});
